### ISSUE TITLE
P-value

### ISSUE THREAD

**Issue by alyssaphelps** [emdupre/hd4630_workshops#12]
Hey Elizabeth,

I'm trying to look at my second-level results in afni and when I set my p-value to .001 and k to 20 (in clusterize) I don't get any activation in the brain. I don't know if its tied to the fact that I'm not able to change my ULay function? 

Thanks again.
![screen shot 2017-03-18 at 2 07 11 pm](https://cloud.githubusercontent.com/assets/25986495/24074724/7d7eb458-0be4-11e7-9223-72da5a8804ca.png)

**Comment by charlenetsai** [comment]
Same for me, when I set the p-value at a higher value (eg. 0.01) I see activations. Are you able to open the clusterize report window?

**Comment by alyssaphelps** [comment]
^^ I cannot!

**Comment by charlenetsai** [comment]
I can at times, but it still wouldn't show any areas highlighted/activated at P<0.001. Do you see activated areas when you set the p to 0.005 or above?

**Comment by emdupre** [comment]
Just to let you both know, I'm looking into this and will report back soon!

**Comment by emdupre** [comment]
This was addressed in the revised midterm question. Please look at the contrast _Incongruent > Baseline_ instead.
