### ISSUE TITLE
Problem with uber_subject.py (again)

### ISSUE THREAD

**Issue by sbhattasali** [emdupre/hd4630_workshops#13]
After I run ./setup/mac/mac_launch.sh, a XQuartz terminal launches and I go to data/Flanker_task and type in uber_subject.py and get the following error:
`uber_subject.py: cannot connect to X server 192.168.0.2:0`

It was working earlier this week so I'm not sure what changed. I looked at ifconfig (screenshot attached) and manually updated the ip address in mac_launch.sh (the default was set to en1 earlier) but it still gives me the same errors. My XQuartz is up to date and it has the correct security preferences. Any ideas about what is going on?

![screen shot 2017-03-18 at 4 16 58 pm](https://cloud.githubusercontent.com/assets/25591137/24075841/a65363dc-0bf9-11e7-8a38-26ce38fa78c3.png)

**Comment by emdupre** [comment]
What you're looking for it to connect to is your active `inet` address. Here it says that your `en1` is active (you can see that in the status of `en1`).  So it sounds like it was trying to connect through the correct address in the first place, but for some reason can't access it. 

From your description, this seems like an XQuartz issue. If you're sure the settings are correct (specifically, that it's allowing connections from network clients), I'd try restarting (1) your user session by logging in and back out again, and (2) your computer. 

If that still yields this same error, can you update here with your XQuartz version?

**Comment by sbhattasali** [comment]
Restarting the user session didn't help but after restarting my computer a couple of times, it worked. 
My XQuartz version is 2.7.11 and I think there might be something weird going on since each of my uber_test.py run is taking almost 2 hours to complete.

**Comment by emdupre** [comment]
Can you run one subject non-graphically, and report the run time here? The steps are as follows:

* Get `uber_subject.py` loaded, and fill in all parameters as though you were going to run it through the gui
* Save the script as we did in class; this should result in a `cmd.*` file
* Run this script by navigating to the directory it's stored in, then running `./<SCRIPT_NAME>` where `<SCRIPT_NAME>` is the name of the `cmd.*` file
* Confirm it generated a `proc.<sub>` script in the same directory, where `<sub>` is the name of the subject you entered in `uber_subject.py`
* Run the `proc.<sub>` script with `tcsh -xef proc.<sub> |& tee output.proc.<sub>`, replacing `<sub>` with your subject name

This should take approximately 40 minutes to run.

**Comment by sbhattasali** [comment]
I tried it without the GUI and it takes an hour. It is definitely quicker this way so I'll just do the rest similarly. Thanks!
