### ISSUE TITLE
Revised Midterm Question

### ISSUE THREAD

**Issue by llc72** [emdupre/hd4630_workshops#15]
Hi! I'm not sure if this is a question that others are allowed to answer - I am not quite sure what is meant by the revisions made to midterm question 5 (where the incongruent > baseline would come into play) and the FYI information on the stimulus timing files. Would it be possible for someone to give a general explanation just to clarify? Thank you!

**Comment by alyssaphelps** [comment]
Hi! Not sure how much I can help, but from what I understand instead of looking at C_I or I_C in uber_ttest we are now just looking at I. Hope that helps!

**Comment by llc72** [comment]
Thank you! This does help a bit.
