### ISSUE TITLE
Saving subject results

### ISSUE THREAD

**Issue by llc72** [emdupre/hd4630_workshops#16]
I'm still having issues saving/seeing subject results. If completed at different sittings, the earlier pre-processing and first level analyses that I run are not showing up in the subject_results folder. Could this be a matter of improperly saving information? I save the scripts generated from the first level analysis, but the individual subject results folders then no longer appear when I start working on another subject.

**Comment by emdupre** [comment]
Make sure to look at #10 for help with this!
