### ISSUE TITLE
Error with subject 21 

### ISSUE THREAD

**Issue by sbhattasali** [emdupre/hd4630_workshops#17]
While running preprocessing and first-level analysis, I am running into an error with subject 21. All the others were fine. I get the following error and it stops right there:

```
ERROR: can't open dataset sub-21_T1w_ns+tlrc
ERROR: Can't read matrix from 'sub-21_T1w_ns+tlrc::WARP_DATA'
```
I tried it a couple of times with the gui and from the command line but I get the same error. It does display the following message but I wasn't sure if I should re-run it with checking the "OK maxite" option since I didn't do it for the other subjects.

```
Warping used up maximum iterations
even after doubling number of iterations to 274.
Convergence might not have been reached.

If you find the alignment poor, try
rerunning the script with a transform
type of fewer parameters (-xform) or by using 
an even higher number of iterations  #(-maxite).
You can also choose to continue with the
current result (dset: __ats_tmp__reg_warpdriveout+orig
by using the option: -OK_maxite
```

**Comment by emdupre** [comment]
You only need to process 15 of the remaining 19 participants, so if you're having an issue with one I would just skip them

**Comment by changy12** [comment]
I have problems with both subjects 16 and 21. Though it said successful with the first level analysis, but there are not "stats.sub_16+tlrc.HEAD", "stats.sub_16+tlrc.BRIK", "stats.sub_21+tlrc.HEAD", "stats.sub_21+tlrc.BRIK". Did anyone have the same problem?
