### ISSUE TITLE
Can't find subject results

### ISSUE THREAD

**Issue by djb298** [emdupre/hd4630_workshops#18]
I have been having issues finding the xmat files and subject results folder. I ran two subjects and got the success messages. However, there is no subject results folder on my computer and I can't see the result. I also enter the "find" script in my terminal and cannot find it. When I go save the script for a subject I ran inside uber subject.py, I can see the subjects results folder exists. How do I get the results folder and the xmat files into my finder/desktop?

**Comment by emdupre** [comment]
Can you provide me with paths for your files? So, run these commands inside the Docker image:

find . -name 'sub-01'
find . -name 'stats*.BRIK'

Can you paste the output here?

**Comment by djb298** [comment]
Attached are what you asked for. I don't know if this is what you meant by
the path for my files.

Dan

**Comment by emdupre** [comment]
The attachment didn't come through. Can you just copy and paste the output of those two commands?

**Comment by djb298** [comment]
Sorry.. heres the output

student@ef605aee2750:~/student$ find . -name 'sub-01'

./data/Flanker_task/sub-01

student@ef605aee2750:~/student$ find . -name 'stats*.BRIK'

./data/Flanker_task/group.grp_01/subj.sub_01/sub_01.results/stats.sub_01+tlrc.BRIK

./data/Flanker_task/group.grp_01/subj.sub_02/sub_02.results/stats.sub_02+tlrc.BRIK

./data/Flanker_task/group.grp_01/subj.sub_03/sub_03.results/stats.sub_03+tlrc.BRIK

./data/Flanker_task/group.grp_01/subj.sub_04/sub_04.results/stats.sub_04+tlrc.BRIK

./data/Flanker_task/group.grp_01/subj.sub_05/sub_05.results/stats.sub_05+tlrc.BRIK

./data/Flanker_task/group.grp_01/subj.sub_06/sub_06.results/stats.sub_06+tlrc.BRIK

./data/Flanker_task/group.grp_01/subj.sub_07/sub_07.results/stats.sub_07+tlrc.BRIK

**Comment by emdupre** [comment]
Thanks! It looks like your files aren't saving correctly. Were you able to save the preprocessing script like we did in class?

Just as a check, can you re-run the following two commands in a new, non-Docker terminal? These were originally run in the [Downloading Data guide](https://emdupre.github.io/hd4630_workshops/pulling-data-mac), but the settings don't seem to be holding for you.

`cd ~/Desktop/hd4630_workshops-master/`
`chmod -R 770 .`

Then if you create a file inside the Docker image with:

`touch test.txt`

can you see it on your local computer?

**Comment by djb298** [comment]
After entering in the touch test.txt command, I can see it in my local
files. I can save the preprocessing script. However, when I click save as,
there is the option to save in subject_results/group.grp_01/subj.sub_08
folder, however that folder doesn't exist on my local computer.

**Comment by emdupre** [comment]
If you 'save as' does it create the folder?

**Comment by djb298** [comment]
I still do not see the folder on my local files, which has been the issue.
Because it seems like the subject results folder exists somewhere, just not
on my local files

**Comment by emdupre** [comment]
So the folders in the `student` directory of the Docker image (i.e., the `code` and `data` folders) are mapped directly to your local drive. So if you created the `subject_results` folder as a sub-folder anywhere within either of those (i.e., even under `Flanker_task`), it will appear on your local drive. This seems to be the case, as you're able to save files within the Docker image and have them appear on your local computer.

When you try to 'save as,' what's the path that's showing in the GUI?

**Comment by djb298** [comment]
The path is /home/student/subject_results/group.grp_01/subj.sub_08

**Comment by emdupre** [comment]
Ok, great! That's the problem. You're running it so that it's saving directly in the `student` directory. When you log on to the Docker image, first change into the folder where the data lives with `cd data/Flanker_task/` then run `uber_subject.py`. 

You can also save the above results by changing the path in the GUI to `/home/student/data/Flanker_task/subject_results/group.grp_01/subj.sub_08`

**Comment by djb298** [comment]
So if I were to change the path in the GUI, would I create an empty subject
results folder?

**Comment by emdupre** [comment]
If you've just set the options in `uber_subject.py` and are now trying to save the preprocessing script, it would create the folders specified in that path (if that don't already exist), and then save the preprocessing script at the listed location. When you run that script, it would place the results in that folder.

**Comment by djb298** [comment]
Okay, so I'm in the process of saving the preprocessing script, and it is
stuck at /home/student/data/Flanker_task and I do not know where to go from
there because there is no subject results folder to continue on the path

**Comment by emdupre** [comment]
What happens if you just save it in `/home/student/data/Flanker_task` but then run it from the GUI, as detailed in the second slide set?

**Comment by djb298** [comment]
I got this as a result, it did not finish running the script and gave me an
error at the bottom


-- setting subj_dir to subject_results/group.grp_01/subj.sub_08

++ writing afni_proc.py command to
subject_results/group.grp_01/subj.sub_08/cmd.ap.sub_08

++ writing as file /home/student/data/Flanker_task/cmd.ap.sub_08 ...

===== ++++ ===== re-running ap_command....

++ executing: tcsh cmd.ap.sub_08 |& tee output.cmd.ap.sub_08

-- setting working dir to subject_results/group.grp_01/subj.sub_08

starting command: tcsh -xef proc.sub_08 |& tee output.proc.sub_08


++ process is started, pid = 186

ERRO[0282] error getting events from daemon: EOF


Dans-MacBook-Pro-2:hd4630_workshops-master danbockelman$

**Comment by emdupre** [comment]
That seems to be an issue with the Docker container, not with your AFNI script. I'd suggest re-starting your computer to take Docker and and background processes offline. Then, when you log back in, re-start Docker, load the image, `cd data/Flanker_task`, and re-run `uber_subject.py`.

Let me know if that still doesn't work!

**Comment by djb298** [comment]
It worked by typing cd data/Flanker_task. I can see the xmat file results.
Thank you so much
