### ISSUE TITLE
There are not "stats.sub_??+tlrc" file for subjects 16 and 21.

### ISSUE THREAD

**Issue by changy12** [emdupre/hd4630_workshops#19]
I have problems with both subjects 16 and 21. Though it said successful with the first level analysis, but there are not "stats.sub_16+tlrc.HEAD", "stats.sub_16+tlrc.BRIK", "stats.sub_21+tlrc.HEAD", "stats.sub_21+tlrc.BRIK". 
Did anyone have the same problem?
Thank you.
       Ziyi Chen

**Comment by emdupre** [comment]
See #17 for a similar issue and resolution.
