### ISSUE TITLE
Exactly what to have and where to get them

### ISSUE THREAD

**Issue by charlenetsai** [emdupre/hd4630_workshops#2]
Hi! 

I'm not sure if it's just me but I was not very clear on the exact steps of what we need to do by next workshop. 

So far I have:

- downloaded **Docker** (the Whale icon is in my applications folder so I know for sure I've downloaded it)
- downloaded **AFNI** from this page (https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/download_links.html) and I got a folder called "macosx_10.7_Intel_64", and I'm not sure what to do about it. 
- downloaded **Elizabeth's files** from here (now its a folder called hd4630_workshops-master, I have it on my desktop)
- clicked into the **Flanker task** and **Stroop task** links (https://openfmri.org/dataset/ds000102/ and https://openfmri.org/dataset/ds000164/ respectively), but I'm not sure which links lead to the data that we want to download 

Am I missing anything that I should be doing?? 

I was not able to type down every command Elizabeth did today in Terminal in class; do we need to be able to do that by next class or will we go over it again? 

I apologize for this lengthy question. For some reason I was just not very clear about what exactly we should have by next class, and what the exact procedures are to get there. 

Thanks for your help!

**Comment by emdupre** [comment]
There will be a full to do list for each OS created soon! Sorry this isn't up yet. For now, here's the quick run through:

* Download Docker or Docker Toolbox, as your operating system allows (check the requirements for each!)
* Make sure you have [XQuartz](https://www.xquartz.org/) on a Mac OSX or [Cygwin/X](http://x.cygwin.com/) on a Windows. 
* With Docker running or in a Docker terminal (see #1 for an explanation of what that is), run `docker pull emdupre/hd4630_workshops/`
* Download this repository and put it on your Desktop
* If you're on a mac, run the `setup/mac/mac_openfmri.sh` and `setup/mac/mac_launch.sh` scripts. If you've never run a script before, follow these steps (Note that these are OS specific!):
  1. Open a Docker Terminal or launch Docker
  2. In the terminal, type `cd` and drag the folder you downloaded from your Desktop into the Terminal. That should add a path, so the terminal looks like 
`cd ~/Desktop/hd4630_workshops-master/`
  3.  Hit Enter, then enter and run `chmod -R 770 .`
  4. Finally, enter and run `./setup/mac/mac_openfmri.sh` and `./setup/mac/mac_launch.sh`
* The `mac_openfmri.sh` script should download the data to your computer for you. The `mac_launch.sh` will open the docker image so you should be able to type `afni` and have the GUI pop up.

Note that you do ***not*** need to download AFNI or the OpenfMRI data on your own!
