### ISSUE TITLE
How to Change Path in GUI? - Same issue as #18

### ISSUE THREAD

**Issue by llc72** [emdupre/hd4630_workshops#20]
I'm still having the same issue as #18. I tried the first method of cd data/Flanker_task/ then ran uber_subject.py and this did not seem to work. I am looking into trying the second method, but I'm not sure how to change the path in the GUI.

**Comment by llc72** [comment]
When I tried the first method, the results saved to my local computer, as opposed to saving in the repository. Therefore, they were not visible when I tried to access the Xmat files.

**Comment by emdupre** [comment]
If you created results within the Docker image and they were saved to your local computer, they are accessible using AFNI. 

Did you try running the `find . -name '*stats*.BRIK` command from #18 ? If so, what was the output?

**Comment by llc72** [comment]
Thank you - I did try the find commands. They are returning that the "command is not found". I have some screenshots saved from my previous attempts last week and will submit these with my midterm. I may inquire in the future about what exactly I may be doing/what is going wrong. Thank you, again!
