### ISSUE TITLE
Final Exam uber_subject.py

### ISSUE THREAD

**Issue by djb298** [emdupre/hd4630_workshops#22]
When preprocessing the first subject for the Stroop task, once I entered in all of the correct values and tried to run the script, I got an error that said:

- applying orig view as +tlrc
** already in tlrc space: -volreg_tlrc_* is not allowed
** invalid block : volreg
----------------------------------------------------------------------
** failed command (create_blocks):

  afni_proc.py -subj_id sub_001 -script proc.sub_001 -scr_overwrite -blocks       \
      tshift align tlrc volreg blur mask scale regress -copy_anat                 \
      /home/student/data/Stroop_task/sub-001/anat/sub-001_T1w.nii.gz              \
      -tcat_remove_first_trs 0 -dsets                                             \
      /home/student/data/Stroop_task/sub-001/func/sub-001_task-stroop_bold.nii.gz \
      -align_opts_aea -giant_move -tlrc_base MNI_avg152T1+tlrc                    \
      -volreg_align_to first -volreg_align_e2a -volreg_tlrc_warp -blur_size       \
      6.4 -regress_stim_times                                                     \
      /home/student/data/Stroop_task/sub-001/func/Stroop_01_Congruent.txt         \
      /home/student/data/Stroop_task/sub-001/func/Stroop_02_Incongruent.txt       \
      /home/student/data/Stroop_task/sub-001/func/Stroop_03_Neutral.txt           \
      -regress_stim_labels Congruent Incongruent Neutral -regress_basis GAM       \
      -regress_censor_motion 0.3 -regress_opts_3dD -gltsym 'SYM: Incongruent      \
      -Congruent' -glt_label 1 I_C -regress_make_ideal_sum sum_ideal.1D           \
      -regress_est_blur_epits -regress_est_blur_errts

**Comment by emdupre** [comment]
Thanks for opening this! It seems as though the header information in the functional file disagrees with what's written in the manuscript. I've commented on the original dataset to try and resolve why this mismatch is occurring, but a short term solution is the following:

With Docker running, navigate to `data/Stroop_data/`. Once there, run the command `find . -name '*bold*' -exec 3drefit -space ORIG {} \;` This should take 5-10 minutes to complete. 
Then try re-running `uber_subject.py` afterwards and let me know if there are any additional errors!

**Comment by djb298** [comment]
That worked that you!

**Comment by juliebarbera** [comment]
does this code have to be run before each of the uber_subject.py runs? or just once?

**Comment by emdupre** [comment]
Only once-- it should iterate through every subject.

**Comment by changy12** [comment]
I have run this code, and it is successful for subjects up to 25. However, the same problem happens again when I run subject 26. I do not know why.
Thank you.

-- applying orig view as +tlrc
** already in tlrc space: -volreg_tlrc_* is not allowed
** invalid block : volreg
----------------------------------------------------------------------
** failed command (create_blocks):

  afni_proc.py -subj_id Stroop_sub26 -script proc.Stroop_sub26 -scr_overwrite                 \
      -blocks tshift align tlrc volreg blur mask scale regress -copy_anat                     \
      /home/student/data/Stroop_task/sub-026/anat/sub-026_T1w.nii.gz                          \
      -tcat_remove_first_trs 0 -dsets                                                         \
      /home/student/data/Stroop_task/sub-026/func/sub-026_task-stroop_bold.nii.gz             \
      -align_opts_aea -giant_move -tlrc_base MNI_avg152T1+tlrc                                \
      -volreg_align_to first -volreg_align_e2a -volreg_tlrc_warp -blur_size                   \
      6.4 -regress_stim_times                                                                 \
      /home/student/data/Stroop_task/Stroop_stim_times/sub-026/func/Stroop_01_Congruent.txt   \
      /home/student/data/Stroop_task/Stroop_stim_times/sub-026/func/Stroop_02_Incongruent.txt \
      /home/student/data/Stroop_task/Stroop_stim_times/sub-026/func/Stroop_03_Neutral.txt     \
      -regress_stim_labels Congruent Incongruent Neutral -regress_basis GAM                   \
      -regress_censor_motion 0.3 -regress_make_ideal_sum sum_ideal.1D                         \
      -regress_est_blur_epits -regress_est_blur_errts

**Comment by emdupre** [comment]
It looks like it didn't apply to subject 26, which makes me think it's in a different location somehow. Just run 
`3drefit -space ORIG /home/student/data/Stroop_task/sub-026/func/sub-026_task-stroop_bold.nii.gz`
and let me know if that fixes the problem. Also make sure to look at the command provided in #23!

**Comment by changy12** [comment]
Thank you, Elizabeth. 
That works well for 26. 
The same problem happens for 27 and 28, so I just change 26 in the command into 27 and 28, yes?
BTW, I did not see any command in #23.

**Comment by emdupre** [comment]
Yes, that's correct.

And sorry, the command is in the other open issue, #25 !
