### ISSUE TITLE
Locating Stroop data

### ISSUE THREAD

**Issue by alyssaphelps** [emdupre/hd4630_workshops#23]
Hi Elizabeth,

I'm a little confused about where all of my Stroop data is. Is it the same as the ds000164_R1.0.0 folder? And then I take all off the Stroop stim files and move them into the func folder for each participant?

Sorry for the confusion!

Thanks.

Alyssa

**Comment by emdupre** [comment]
Yes, that's correct!

**Comment by charlenetsai** [comment]
Is your grab_onsets_Stroop.py supposed to work in Matlab?? Sorry I don't know how to utilize those codes or where ..

**Comment by emdupre** [comment]
It's a python script, but you don't need to run it yourself. The created timing files are in the dropbox folder.
