### ISSUE TITLE
I_C AFNI results

### ISSUE THREAD

**Issue by alyssaphelps** [emdupre/hd4630_workshops#25]
Hi Elizabeth,

I was able to preprocess all of my participants and run 3dttest but I don't see any activation for the I>C contrast at a threshold of p>.001. I attached the options I selected for 3dttest. Any ideas?

Thank you!

Alyssa
![3dttest_final](https://cloud.githubusercontent.com/assets/25986495/26036090/588fd51c-38a5-11e7-88f7-c43599e75305.png)

**Comment by charlenetsai** [comment]
Exactly same situation for me!

**Comment by djb298** [comment]
I am also having the same issue!

**Comment by emdupre** [comment]
Nathan should be issuing an announcement about this soon. Somehow the data uploaded to openfMRI had incorrect header information&mdash; you may have noticed this as AFNI updating that the stimulus timing exceeded the run length. 

If you're interested in changing this, you'd run a modified version of the command provided in #22. The exact command is: `find . -name '*bold*' -exec 3drefit -TR 1.5 {} \;`

You'd then re-process the subjects with uber_subject.py.

**Comment by alyssaphelps** [comment]
I actually saw that post and ran that code before I preprocessed any of my participants. I see activation for all of the individual brains and even some scattered activation for the 3dttest brain but not at the .001 level.

**Comment by emdupre** [comment]
The command listed above and in #22 are different, and you'd need to run both!

**Comment by charlenetsai** [comment]
So we have to first run that code, and then re-run uber_subject.py for every subject?

**Comment by emdupre** [comment]
Yes, to get correct activation profiles at the group level you would need to run this command (and the command from #22) before running uber_subject.py !
