### ISSUE TITLE
Can't load dataset '/home/student/data/Stroop_task/sub-017/func/sub-017_task-stroop_bold.nii.gz

### ISSUE THREAD

**Issue by changy12** [emdupre/hd4630_workshops#26]
Hello, Elizabeth.
I faced this error: "Can't load dataset '/home/student/data/Stroop_task/sub-017/func/sub-017_task-stroop_bold.nii.gz': is it complete?”

So is 24 and I remember also 8.

Thank you.

**Comment by emdupre** [comment]
I haven't seen that error. Maybe when you downloaded from openfMRI those scans were corrupted? This could have happened if you interrupted the download at some point (e.g., by closing your computer). 

I'd try downloading those subjects again [here](https://openfmri.org/dataset/ds000164/) to see if that fixes your problem.

**Comment by changy12** [comment]
It works now. Thanks.
