### ISSUE TITLE
Error while running mac_launch.sh

### ISSUE THREAD

**Issue by sbhattasali** [emdupre/hd4630_workshops#3]
When I run mac_launch.sh from the Docker terminal, I get the following error message:

```
docker: open /mnt/sda1/var/lib/docker/tmp/GetImageBlob701389093: read-only file system.
See 'docker run --help'.
```

I tried to look at the run documentation but it gives me a bunch of flags and I'm not sure which one I should be using.

**Comment by emdupre** [comment]
There are a couple of things that could be causing this... could you please run `docker run -ti --rm emdupre/hd4630_workshops` and let me know if that opens the image successfully? Your prompt should change so that the user ID is 'student,' though AFNI will not open correctly.

**Comment by emdupre** [comment]
Closed following in-class discussion.
