### ISSUE TITLE
trouble building Docker image on mac

### ISSUE THREAD

**Issue by cam543** [emdupre/hd4630_workshops#6]
Hi!

So I downloaded and installed Docker, downloaded the repository (hd4630_workshops-master) to my desktop, downloaded the Docker image, and then tried to run this:

TLMs-Mac-Pro:~ TLM$ docker build -t emdupre/hd4630_workshops .

and got this:

unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat 
/Users/TLM/Dockerfile: no such file or directory

So then I just created a file /Users/TLM/Dockerfile and tried it again. It ran, and after a few minutes I got this message:

TLMs-Mac-Pro:~ TLM$ docker build -t emdupre/hd4630_workshops .
ERRO[0532] Can't add file /Users/TLM/.docker/machine/machines/default/disk.vmdk to tar: archive/tar: write too long 

but it kept running. And then a few minutes later I got this message:

ERRO[1090] Can't add file /Users/TLM/Library/Caches/CloudKit/CloudKitMetadata-wal to tar: archive/tar: write too long 

but it kept running. Then it froze and asked if the Dockerfile was empty. What should I be doing here?

Thanks!

**Comment by emdupre** [comment]
Did you try `docker pull emdupre/hd4630_workshops`? If it failed, what was the error message?

**Comment by emdupre** [comment]
Closed following in-class discussion.
