### ISSUE TITLE
Downloading OpenfMRI Data

### ISSUE THREAD

**Issue by alyssaphelps** [emdupre/hd4630_workshops#7]
Hi Elizabeth,

I downloaded docker and the relevant files from github, but now I'm at a loss as to how to download the openfmri data. I've located the Stroop task - do I click each of these links to download?
_Data Associated with Revision:
Data for all subjects (1.5 GB)
Metadata (3 KB)_
Do they need to/Can they go in a specific folder on my computer or just the desktop?

Thank you!

Alyssa

**Comment by emdupre** [comment]
Hi Alyssa,

You should download "Data for all subjects (1.5GB)" and unzip it into a folder on your Desktop called `hd4630_workshops-master\data` (assuming you're on a Windows machine). If you downloaded this git repository to your desktop, that should just involve creating a new folder called `data` and unzipping the files inside of it.

Let me know if that clarifies things!
