### ISSUE TITLE
trouble pulling up afni

### ISSUE THREAD

**Issue by llc72** [emdupre/hd4630_workshops#8]
I reached the step where I have typed in "afni", but then receive the error message related to X11 shown below. If possible please advise. Thank you! 

![docker windows x11 error](https://cloud.githubusercontent.com/assets/26077166/23389702/cecbd676-fd37-11e6-9c89-732e627e027f.jpg)

**Comment by emdupre** [comment]
Did you set the Xming settings as detailed [here](https://emdupre.github.io/hd4630_workshops/installing-xming)?

**Comment by llc72** [comment]
Yes, I believe so. Is there a way to double check, though?

**Comment by llc72** [comment]
Or, could the error be due to something else?

**Comment by emdupre** [comment]
The error is coming from your X11 set up, so I'd first confirm that the settings are correct. You can double-check them just by reopening Xlaunch. You may need to sign out so that the settings take effect. If that doesn't solve the error, let me know!

**Comment by llc72** [comment]
Yes, it worked! Thank you! I think I inputted the settings before restarting my computer. I don't think the settings changes held after the restart.

**Comment by emdupre** [comment]
Great, glad that worked! Thanks for confirming 👍
