### ISSUE TITLE
uber_subject.py midterm

### ISSUE THREAD

**Issue by alyssaphelps** [emdupre/hd4630_workshops#9]
Hi Elizabeth!

Just to clarify, we need to run uber_subject 22 times, correct? Once for each subject? Then we can go onto second-level analysis.

Alyssa

**Comment by emdupre** [comment]
Hi Alyssa,

You should only run 15 additional subjects. You can then combine these with the 7 provided subjects to have 22 subjects for the second level analysis. If you ran an additional 22 subjects for the exam, you'd end up re-preprocessing ones you were given in class!

Hth,

Elizabeth
